name: groknotes
favicon: null
layout_spectrum: 0.25755
typography_spectrum: 0.40294
title: Grok Notes - A markdown editor/viewer for android
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.32099274166016867
  saturation: 0.5334555457552427
  rhythmicContrast: 0.06499765464425089
purpose:
  - name: null
    item: null
    url: null
